apiVersion: v1
kind: Pod
metadata:
  name: result-app-Pod
  labels:
    name: result-app-Pod
    app: G1
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports: 
        - containerPort: 80
             