apiVersion: v1
kind: Pod
metadata:
  name: voting-app-Pod
  labels:
    name: voting-app-Pod
    app: G1
spec:
  containers:
     - name: voting-app
       image: dockersamples/examplevotingapp_vote
       ports: 
         - containerPort: 80
             